# Generated by Django 5.1 on 2024-08-22 08:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 22, 8, 25, 4, 624133, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default="2024-08-04"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("speaker", models.CharField(blank=True, max_length=255, null=True)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
