# Generated by Django 5.1 on 2024-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_section_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="availability",
            field=models.CharField(
                choices=[("all", "All Users"), ("specific", "Specific Users")],
                default="all",
                max_length=10,
            ),
        ),
    ]
