# Generated by Django 5.1 on 2024-08-26 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_participants_event_user_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="join_datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
