# Generated by Django 5.1 on 2024-08-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_participant_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="user_participants",
        ),
    ]
