# Generated by Django 5.1 on 2024-10-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_event_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WaitingList",
        ),
    ]
