# Generated by Django 5.1 on 2024-10-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_delete_waitinglist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"verbose_name": "Section", "verbose_name_plural": "Sections"},
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="event",
            table="events",
        ),
        migrations.AlterModelTable(
            name="participant",
            table="participants",
        ),
        migrations.AlterModelTable(
            name="section",
            table="sections",
        ),
    ]
