# Generated by Django 5.1 on 2024-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_alter_ticket_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
