# Generated by Django 5.1 on 2024-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("hosting", "Hosting"), ("normal", "Normal User")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
