# Generated by Django 5.1 on 2024-08-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        choices=[
                            (
                                "what the number of your family?",
                                "What the number of your family?",
                            ),
                            (
                                "what the name of your best friend?",
                                "What the name of your best friend?",
                            ),
                            (
                                "what the name of your first company work?",
                                "What the name of your first company work?",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
