# Generated by Django 5.1 on 2024-10-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.DeleteModel(
            name="SecurityQuestion",
        ),
    ]
