# Generated by Django 5.1 on 2024-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_messagegroup_eventgroupmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventgroupmessage",
            name="image_content",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/chat_group_images/"
            ),
        ),
        migrations.AlterField(
            model_name="usergroupmessage",
            name="image_content",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/chat_users_images/"
            ),
        ),
    ]
