# Generated by Django 5.1 on 2024-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_eventgroupmessage_image_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventgroupmessage",
            name="image_content",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_group_images/"
            ),
        ),
        migrations.AlterField(
            model_name="usergroupmessage",
            name="image_content",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_users_images/"
            ),
        ),
    ]
