# Generated by Django 5.1 on 2024-10-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_eventgroupmessage_image_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventgroupmessage",
            options={
                "verbose_name": "GroupMessage",
                "verbose_name_plural": "GroupMessages",
            },
        ),
        migrations.AlterModelOptions(
            name="usergroupmessage",
            options={
                "verbose_name": "UserMessage",
                "verbose_name_plural": "UserMessages",
            },
        ),
        migrations.AlterModelTable(
            name="eventgroupmessage",
            table="group_messages",
        ),
        migrations.AlterModelTable(
            name="usergroupmessage",
            table="user_messages",
        ),
    ]
