# Generated by Django 5.1 on 2024-10-25 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_eventgroupmessage_options_and_more"),
        ("events", "0015_alter_category_options_alter_event_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "image_content",
                    models.ImageField(
                        blank=True, null=True, upload_to="messages_image/"
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "message",
            },
        ),
        migrations.AlterField(
            model_name="eventgroupmessage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_messages",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="usergroupmessage",
            name="image_content",
            field=models.ImageField(blank=True, null=True, upload_to="messages_image/"),
        ),
        migrations.AlterField(
            model_name="usergroupmessage",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receive_user_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usergroupmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_user_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="eventgroupmessage",
            table="group_message",
        ),
        migrations.AlterModelTable(
            name="usergroupmessage",
            table="user_message",
        ),
        migrations.CreateModel(
            name="EventMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="events.event",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(related_name="event", to="chat.message"),
                ),
            ],
            options={
                "verbose_name": "EventMessage",
                "verbose_name_plural": "EventMessages",
                "db_table": "event_message",
            },
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.ManyToManyField(to="chat.message")),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserMessages",
                "verbose_name_plural": "UserMessages",
                "db_table": "user_messages",
                "unique_together": {("sender", "receiver")},
            },
        ),
    ]
